image: nativecode/node-build:latest

services:
  - nativecode/node-build:latest

stages:
  - build
  - merge
  - publish

continuous:
  stage: build
  except:
    - develop
    - master
    - tags
  script:
    - npm ci
    - npm run build || exit 1
    - npx semantic-release -d
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

merge:
  stage: merge
  only:
    - merge_requests
  script:
    - npm ci
    - npm run build || exit 1
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

prepare:
  stage: publish
  only:
    - develop
    - master
  script:
    - npm ci
    - npm run build || exit 1
    - npx semantic-release
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

release:
  stage: publish
  only:
    - tags
  script:
    - echo -n $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
    - PACKAGE_VERSION=$(git describe --abbrev=0 --tags)
    - npm ci
    - npm run build || exit 1
    - docker build --rm -t nativecode/plexify . || exit 1
    - docker tag nativecode/plexify nativecode/plexify:${PACKAGE_VERSION} || exit 1
    - docker push nativecode/plexify:${PACKAGE_VERSION} || exit 1
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    GIT_SUBMODULE_STRATEGY: recursive
