image: nativecode/node-build:latest

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_SHORT_SHA"
  paths:
    - bin
  policy: push

stages:
  - build
  - publish

services:
  - nativecode/node-build:latest

before_script:
  - source .ci-env.sh
  - echo -n $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
  - .citools/setup-git ${BUILD_REPO_BRANCH} ${BUILD_REPO_GIT} ${BUILD_REPO_EMAIL}
  - .citools/setup-ssh ${BUILD_REPO_DOMAIN} ${BUILD_REPO_SSHKEY_PATH} ${BUILD_REPO_DOMAIN_SSH}

continuous:
  stage: build
  except:
    - develop
    - master
    - tags
  script:
    - npm ci
    - npm run build
    - npx semantic-release -d
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

prepare:
  stage: publish
  only:
    - develop
    - master
  cache:
    key: "$CI_JOB_STAGE-$CI_COMMIT_SHORT_SHA"
    paths:
      - bin
    policy: push
  script:
    - npm ci
    - npm run build
    - npx semantic-release
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

release:
  stage: publish
  only:
    - tags
  cache:
    key: "$CI_JOB_STAGE-$CI_COMMIT_SHORT_SHA"
    paths:
      - bin
    policy: pull
  script:
    - PACKAGE_VERSION=$(git describe --abbrev=0 --tags)
    - docker build --rm -t nativecode/plexify . || exit 1
    - docker tag nativecode/plexify nativecode/plexify:${PACKAGE_VERSION} || exit 1
    - docker tag nativecode/plexify nativecode/plexify:latest || exit 1
    - docker push nativecode/plexify:${PACKAGE_VERSION} || exit 1
    - docker push nativecode/plexify:latest || exit 1
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    GIT_SUBMODULE_STRATEGY: recursive
