image: nativecode/node-build:latest

stages:
  - build

services:
  - nativecode/node-build:latest

before_script:
  - source .ci-env.sh
  - echo -n $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
  - .citools/setup-git ${BUILD_REPO_BRANCH} ${BUILD_REPO_GIT} ${BUILD_REPO_EMAIL}
  - .citools/setup-ssh ${BUILD_REPO_DOMAIN} ${BUILD_REPO_SSHKEY_PATH} ${BUILD_REPO_DOMAIN_SSH}

master:
  stage: build
  only:
    - master
  script:
    - PACKAGE_VERSION=v$(cat package.json | jq -r '.version')
    - docker build --rm -t nativecode/plexify . || exit 1
    - docker tag nativecode/plexify nativecode/plexify:$PACKAGE_VERSION || exit 1
    - docker push nativecode/plexify:$PACKAGE_VERSION || exit 1
    - docker tag nativecode/plexify nativecode/plexify:latest || exit 1
    - docker push nativecode/plexify:latest || exit 1
  variables:
    DOCKER_HOST: tcp://localhost:2375
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

develop:
  stage: build
  only:
    - develop
  script:
    - docker build --rm -t nativecode/plexify . || exit 1
    - docker tag nativecode/plexify nativecode/plexify:next-${CI_COMMIT_SHA:0:8} || exit 1
    - docker push nativecode/plexify:next-${CI_COMMIT_SHA:0:8} || exit 1
    - docker tag nativecode/plexify nativecode/plexify:next || exit 1
    - docker push nativecode/plexify:next || exit 1
  variables:
    DOCKER_HOST: tcp://localhost:2375
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
